OnTrak/Models/Entities/Body/BodyArea.cs
using OnTrak.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Models.Entities.Body
{
    public class BodyArea
    {
        public int BodyAreaId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Byte[] Image { get; set; }

    }
}

OnTrak/Controllers/BodyAreaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnTrak.Models.Data.EFRepo;
using OnTrak.Models.Data.Repository;
using OnTrak.Models.Entities;
using OnTrak.Models.Entities.Body;
using OnTrak.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Controllers
{
    public class BodyAreaController : Controller
    {
        private IBodyAreaRepository bodyAreaRepository;
        private IBodyPartRepository bodyPartRepository;
        private IMuscleRepository muscleRepository;
         
        public DBGetter dbGetter = new DBGetter();
        public BodyAreaController(IBodyAreaRepository bAreaRepo, IBodyPartRepository bPartRepo, IMuscleRepository muscleRepo)
        {
            bodyAreaRepository = bAreaRepo;
            bodyPartRepository = bPartRepo;
            muscleRepository = muscleRepo;
            dbGetter.AssignData(muscleRepository.Muscles.ToList(), bodyAreaRepository.BodyAreas.ToList(), bodyPartRepository.BodyParts.ToList());
        }

        public ViewResult Index() => View(bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
        public ViewResult Edit(int? Id) {
            return View(bodyAreaRepository.CreateBAreaViewModel(bodyPartRepository, Id, dbGetter));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BodyAreaViewModel bodyAreaModel, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            BodyArea bArea = new BodyArea
            {
                BodyAreaId = bodyAreaModel.BodyAreaId,
                Name = bodyAreaModel.Name,
                Description = bodyAreaModel.Description,
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    bArea.Image = memoryStream.ToArray();
                }
            }
            else
            {
                bArea.Image = bodyAreaRepository.GetBodyAreaById(bodyAreaModel.BodyAreaId).Image;
            }


            if (ModelState.IsValid)
            {
                bodyAreaRepository.SaveBodyArea(bArea);
                TempData["Message"] = $"{bArea.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
                return View(bodyAreaModel);
        }

        public ActionResult RetrieveImage(int Id)
        {

            byte[] cover = GetImageFromDataBase(Id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var photo = bodyAreaRepository.GetBodyAreaById(Id).Image;
            byte[] cover = photo;
            return cover;
        }
    }
}

OnTrak/Controllers/BodyPartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnTrak.Models.Data.EFRepo;
using OnTrak.Models.Data.Repository;
using OnTrak.Models.Entities;
using OnTrak.Models.Entities.Body;
using OnTrak.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Controllers
{
    public class BodyPartController : Controller
    {

        private IBodyAreaRepository bodyAreaRepository;
        private IBodyPartRepository bodyPartRepository;
        private IMuscleRepository muscleRepository;
        public DBGetter dbGetter = new DBGetter();
        public BodyPartController(IBodyAreaRepository bAreaRepo, IBodyPartRepository bPartRepo, IMuscleRepository muscleRepo)
        {
            bodyAreaRepository = bAreaRepo;
            bodyPartRepository = bPartRepo;
            muscleRepository = muscleRepo;
            dbGetter.AssignData(muscleRepository.Muscles.ToList(), bodyAreaRepository.BodyAreas.ToList(), bodyPartRepository.BodyParts.ToList());
        }

        public ViewResult Create()
        {
            BodyPartsViewModel bPartVM = new BodyPartsViewModel
            {
                BodyAreas = bodyAreaRepository.BodyAreas.ToList()
            };
            return View(bPartVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BodyPartsViewModel bodyPart, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            BodyPart bPart = new BodyPart
            {
                BodyPartId = bodyPart.BodyPartId,
                Name = bodyPart.Name,
                Description = bodyPart.Description,
                BodyAreaId = bodyPart.BodyAreaId,
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    bPart.Image = memoryStream.ToArray();
                }
            }

            if (ModelState.IsValid)
            {
                bodyPartRepository.SaveBodyPart(bPart);
                TempData["Message"] = $"{bodyPart.Name} has been created";
                return RedirectToAction("Index", "BodyArea", bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
            }
            else
                return RedirectToAction("Index", "BodyArea", bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
        }


        public ViewResult Edit(int? Id)
        {
            return View(bodyPartRepository.CreateBPartViewModel(bodyAreaRepository, Id, dbGetter));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BodyPartsViewModel bodyPartVM, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            BodyPart bPart = new BodyPart
            {
                BodyPartId = bodyPartVM.BodyPartId,
                Name = bodyPartVM.Name,
                Description = bodyPartVM.Description,
                BodyAreaId = bodyPartVM.BodyAreaId,
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    bPart.Image = memoryStream.ToArray();
                }
            }
            else
            {
                bPart.Image = bodyPartRepository.GetBodyPartById(bPart.BodyPartId).Image;
            }


            if (ModelState.IsValid)
            {
                bodyPartRepository.SaveBodyPart(bPart);
                TempData["Message"] = $"{bPart.Name} has been saved";
                return RedirectToAction("Index", "BodyArea");
            }
            else
                return View(bodyPartVM);
        }

        public ActionResult RetrieveImage(int Id)
        {

            byte[] cover = GetImageFromDataBase(Id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var photo = bodyPartRepository.GetBodyPartById(Id).Image;
            byte[] cover = photo;
            return cover;
        }
    }
}

OnTrak/Controllers/ExerciseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnTrak.Models.Data.EFRepo;
using OnTrak.Models.Data.Repository;
using OnTrak.Models.Entities.Activities;
using OnTrak.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Controllers
{
    public class ExerciseController : Controller
    {

        private IBodyAreaRepository bodyAreaRepository;
        private IBodyPartRepository bodyPartRepository;
        private IMuscleRepository muscleRepository;
        private IExerciseRepository exerciseRepository;
        public DBGetter dbGetter = new DBGetter();
        public ExerciseController(IBodyAreaRepository bAreaRepo, IBodyPartRepository bPartRepo, IMuscleRepository muscleRepo, IExerciseRepository exerciseRepo)
        {
            bodyAreaRepository = bAreaRepo;
            bodyPartRepository = bPartRepo;
            muscleRepository = muscleRepo;
            exerciseRepository = exerciseRepo;
            dbGetter.AssignData(muscleRepository.Muscles.ToList(), bodyAreaRepository.BodyAreas.ToList(), bodyPartRepository.BodyParts.ToList());
        }

        public ViewResult Index() {
            return View();
        }

        public ViewResult Create()
        {
            ExerciseViewModel exerciseVM = new ExerciseViewModel
            {
                BodyParts = bodyPartRepository.BodyParts.ToList(),
                BodyAreas = bodyAreaRepository.BodyAreas.ToList(),
                Muscles = muscleRepository.Muscles.ToList()
            };
            return View(exerciseVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExerciseViewModel exerciseVM, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            Exercise exercise = new Exercise
            {
               
                Description = exerciseVM.Description,
                Name = exerciseVM.Name,
                ExerciseId = exerciseVM.ExerciseId,
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    exercise.Image = memoryStream.ToArray();
                }
            }

            if (ModelState.IsValid)
            {
                exerciseRepository.SaveExercise(exercise);
                TempData["Message"] = $"{exercise.Name} has been created";
                return RedirectToAction("Index", "BodyArea", bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
            }
            else
                return RedirectToAction("Index", "BodyArea", bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
        }



        public ViewResult Edit(int? Id)
        {
            return View(muscleRepository.GetMusceById(Id).CreateMuscleViewModel(dbGetter));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ExerciseViewModel exerciseVM, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            Exercise exercise = new Exercise
            {
                Description = exerciseVM.Description,
                Name = exerciseVM.Name,
                ExerciseId = exerciseVM.ExerciseId,
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    exercise.Image = memoryStream.ToArray();
                }
            }
            else
            {
                exercise.Image = exerciseRepository.GetExerciseById(exercise.ExerciseId).Image;
            }


            if (ModelState.IsValid)
            {
                exerciseRepository.SaveExercise(exercise);
                TempData["Message"] = $"{exercise.Name} has been saved";
                return RedirectToAction("Index", "BodyArea");
            }
            else
                return View(exerciseVM);
        }



        public ActionResult RetrieveImage(int Id)
        {

            byte[] cover = GetImageFromDataBase(Id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var photo = muscleRepository.GetMusceById(Id).Image;
            byte[] cover = photo;
            return cover;
        }
    }
}

OnTrak/Controllers/MuscleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnTrak.Migrations;
using OnTrak.Models.Data.EFRepo;
using OnTrak.Models.Data.Repository;
using OnTrak.Models.Entities.Body;
using OnTrak.Models.Repository.BodyData;
using OnTrak.Models.ViewModel;
using OnTrak.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Controllers
{
    public class MuscleController : Controller
    {

        private IBodyAreaRepository bodyAreaRepository;
        private IBodyPartRepository bodyPartRepository;
        private IMuscleRepository muscleRepository;
        public DBGetter dbGetter = new DBGetter();
        public MuscleController(IBodyAreaRepository bAreaRepo, IBodyPartRepository bPartRepo, IMuscleRepository muscleRepo)
        {
            bodyAreaRepository = bAreaRepo;
            bodyPartRepository = bPartRepo;
            muscleRepository = muscleRepo;
            dbGetter.AssignData(muscleRepository.Muscles.ToList(), bodyAreaRepository.BodyAreas.ToList(), bodyPartRepository.BodyParts.ToList());
        }



        public ViewResult Create()
        {
            MuscleViewModel muscleVM = new MuscleViewModel
            {
                BodyParts = bodyPartRepository.BodyParts.ToList()
            };
            return View(muscleVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MuscleViewModel muscleVM, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            Muscle muscle = new Muscle
            {
               BodyPartId = muscleVM.BodyPartId,
               Description = muscleVM.Description,
               Image = muscleVM.Image,
               MuscleId = muscleVM.MuscleId,
               Name = muscleVM.Name
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    muscle.Image = memoryStream.ToArray();
                }
            }

            if (ModelState.IsValid)
            {
                muscleRepository.SaveMuscle(muscle);
                TempData["Message"] = $"{muscle.Name} has been created";
                return RedirectToAction("Index", "BodyArea", bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
            }
            else
                return RedirectToAction("Index", "BodyArea", bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
        }



        public ViewResult Edit(int? Id)
        {
            return View(muscleRepository.getMusceById(Id).CreateMuscleViewModel(dbGetter));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MuscleViewModel muscleVM, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            Muscle muscle = new Muscle
            {
                BodyPartId = muscleVM.BodyPartId,
                Name = muscleVM.Name,
                Description = muscleVM.Description,
                MuscleId = muscleVM.MuscleId
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    muscle.Image = memoryStream.ToArray();
                }
            }
            else
            {
                muscle.Image = muscleRepository.getMusceById(muscle.MuscleId).Image;
            }


            if (ModelState.IsValid)
            {
                muscleRepository.SaveMuscle(muscle);
                TempData["Message"] = $"{muscle.Name} has been saved";
                return RedirectToAction("Index", "BodyArea");
            }
            else
                return View(muscleVM);
        }



        public ActionResult RetrieveImage(int Id)
        {

            byte[] cover = GetImageFromDataBase(Id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var photo = muscleRepository.getMusceById(Id).Image;
            byte[] cover = photo;
            return cover;
        }
    }
}

OnTrak/Views/BodyArea/Edit.cshtml
@model OnTrak.Models.ViewModel.BodyAreaViewModel
@using OnTrak.Models.UIModel

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <h4>BodyArea</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data" method="post">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.HiddenFor(Id => Model.BodyAreaId)
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <div><img class="img-thumbnail" src="/BodyArea/RetrieveImage/@Model.BodyAreaId" alt="" /></div>
                    <input type="file" accept="image/*" name="file" multiple />
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
                <ul>
                    @foreach (var bPart in Model.BodyParts)
                    {
                    <li>
                        @bPart.Name @Html.Partial("_TableButtonsPartial", new SmallButtonModel { BodyPartId = bPart.BodyPartId })
                        <div><img class="img-thumbnail" src="/BodyPart/RetrieveImage/@bPart.BodyPartId" alt="" /></div>
                    </li>
                    }
                </ul>
                <a type="button" class="btn btn-dark " href="@Url.Action("Create", "BodyPart")">
                    Add A Body Part
                </a>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

OnTrak/Views/BodyArea/Index.cshtml
@model IEnumerable<BodyAreaViewModel>
@using OnTrak.Models.UIModel
@using OnTrak.Models.ViewModel
@using OnTrak.Models.Data.EFRepo

@foreach (var bodyArea in Model)
{
    <div class="card card-group m-1 p-1">
        <h3>
            @bodyArea.Name
        </h3>
        <div><img class="img-thumbnail" src="/BodyArea/RetrieveImage/@bodyArea.BodyAreaId" alt="" /></div>
        <div>@bodyArea.Description</div> <br />
        <h4>Body Part</h4><br />
        @if (bodyArea.BodyParts.Count == 0)
        {<div>The are currently no parts for this category</div>}
        else
        {

            <ul>
                @foreach (var part in bodyArea.BodyParts)
                {
                <li>
                    @part.Name
                    <h4>Muscles</h4><br />
                    @if (bodyArea.BodyParts.Count == 0)
                    {<div>The are currently no parts for this category</div>}
                    else
                    {
                        <ul>
                            @foreach (var muscle in part.Muscles)
                            {
                                <li>
                                    @Html.Partial("_SmallButtonPartial", new SmallButtonModel { MuscleId = muscle.MuscleId, Text = muscle.Name, Action = "Edit" })
                                    <div><img class="img-thumbnail" src="/Muscle/RetrieveImage/@muscle.MuscleId" alt="" /></div>
                                </li>
                            }
                        </ul>
                    }
                </li>
                }
                    </ul>
                }
                @Html.Partial("_TableButtonsPartial", new SmallButtonModel { BodyAreaId = bodyArea.BodyAreaId })
            </div>
        }

        <a type="button" class="btn btn-dark " href="@Url.Action("Create", "BodyPart")">
            Add A Body Part
        </a>
        <a type="button" class="btn btn-dark " href="@Url.Action("Create", "Muscle")">
            Add A Muscle
        </a>
        <a type="button" class="btn btn-dark " href="@Url.Action("Create", "Exercise")">
            Add An Exercise
        </a>