OnTrak/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnTrak.Models.Entities.User;
using OnTrak.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Controllers
{
    public class AdminController : Controller
    {
        private IUserValidator<AppUser> userValidator;
        private IPasswordValidator<AppUser> passwordValidator;
        private IPasswordHasher<AppUser> passwordHasher;

        public AdminController(UserManager<AppUser> usrMgr, IUserValidator<AppUser> userValid, IPasswordValidator<AppUser> passValid, IPasswordHasher<AppUser> passwordHash)
        {
            userManager = usrMgr;
            userValidator = userValid;
            passwordValidator = passValid;
            passwordHasher = passwordHash;
        }

        private UserManager<AppUser> userManager;
        //public AdminController(UserManager<AppUser> usrMgr)
        //{
        //    userManager = usrMgr;
        //}

        public ViewResult Index() => View(userManager.Users);
        public ViewResult Create() => View();
        public async Task<IActionResult> Edit(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                return View(user);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, string email, string password)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                user.Email = email;
                IdentityResult validEmail = await userValidator.ValidateAsync(userManager, user);
                if (!validEmail.Succeeded)
                {
                    AddErrorsFromResult(validEmail);
                }
                IdentityResult validPass = null;
                if (!string.IsNullOrEmpty(password))
                {
                    validPass = await passwordValidator.ValidateAsync(userManager, user, password);
                    if (validPass.Succeeded)
                    {
                        user.PasswordHash = passwordHasher.HashPassword(user, password);
                    }
                    else
                    {
                        AddErrorsFromResult(validPass);
                    }
                }
                if ((validEmail.Succeeded && validPass == null) || (validEmail.Succeeded && password != string.Empty && validPass.Succeeded))
                {
                    IdentityResult result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddErrorsFromResult(result);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "User Not Found");
            }
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppUser user = new AppUser
                {
                    UserName = model.Name,
                    Email = model.Email,
                };
                IdentityResult result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");

                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "User Not Found");
            }

            return View("Index", userManager.Users);
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

OnTrak/Controllers/BodyAreaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnTrak.Models.Data.EFRepo;
using OnTrak.Models.Data.Repository;
using OnTrak.Models.Entities;
using OnTrak.Models.Entities.Body;
using OnTrak.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Controllers
{
    public class BodyAreaController : Controller
    {
        private IBodyAreaRepository bodyAreaRepository;
        private IBodyPartRepository bodyPartRepository;
        private IMuscleRepository muscleRepository;
         
        public DBGetter dbGetter = new DBGetter();
        public BodyAreaController(IBodyAreaRepository bAreaRepo, IBodyPartRepository bPartRepo, IMuscleRepository muscleRepo)
        {
            bodyAreaRepository = bAreaRepo;
            bodyPartRepository = bPartRepo;
            muscleRepository = muscleRepo;
            dbGetter.AssignData(muscleRepository.Muscles.ToList(), bodyAreaRepository.BodyAreas.ToList(), bodyPartRepository.BodyParts.ToList());
        }

        public ViewResult Index() => View(bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
        public ViewResult Edit(int? Id) {
            return View(bodyAreaRepository.CreateBAreaViewModel(bodyPartRepository, Id, dbGetter));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BodyAreaViewModel bodyAreaModel, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            BodyArea bArea = new BodyArea
            {
                BodyAreaId = bodyAreaModel.BodyAreaId,
                Name = bodyAreaModel.Name,
                Description = bodyAreaModel.Description,
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    bArea.Image = memoryStream.ToArray();
                }
            }
            else
            {
                bArea.Image = bodyAreaRepository.GetBodyAreaById(bodyAreaModel.BodyAreaId).Image;
            }


            if (ModelState.IsValid)
            {
                bodyAreaRepository.SaveBodyArea(bArea);
                TempData["Message"] = $"{bArea.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
                return View(bodyAreaModel);
        }

        public ActionResult RetrieveImage(int Id)
        {

            byte[] cover = GetImageFromDataBase(Id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var photo = bodyAreaRepository.GetBodyAreaById(Id).Image;
            byte[] cover = photo;
            return cover;
        }
    }
}

OnTrak/Controllers/ExerciseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnTrak.Models.Data.EFRepo;
using OnTrak.Models.Data.Repository;
using OnTrak.Models.Entities.Activities;
using OnTrak.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Controllers
{
    public class ExerciseController : Controller
    {

        private IBodyAreaRepository bodyAreaRepository;
        private IBodyPartRepository bodyPartRepository;
        private IMuscleRepository muscleRepository;
        private IExerciseRepository exerciseRepository;
        public DBGetter dbGetter = new DBGetter();
        public ExerciseController(IBodyAreaRepository bAreaRepo, IBodyPartRepository bPartRepo, IMuscleRepository muscleRepo, IExerciseRepository exerciseRepo)
        {
            bodyAreaRepository = bAreaRepo;
            bodyPartRepository = bPartRepo;
            muscleRepository = muscleRepo;
            exerciseRepository = exerciseRepo;
            dbGetter.AssignData(muscleRepository.Muscles.ToList(), bodyAreaRepository.BodyAreas.ToList(), bodyPartRepository.BodyParts.ToList());
        }

        public ViewResult Index() {
            return View();
        }

        public ViewResult Create()
        {
            ExerciseViewModel exerciseVM = new ExerciseViewModel
            {
                BodyParts = bodyPartRepository.BodyParts.ToList(),
                BodyAreas = bodyAreaRepository.BodyAreas.ToList(),
                Muscles = muscleRepository.Muscles.ToList()
            };
            return View(exerciseVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExerciseViewModel exerciseVM, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            Exercise exercise = new Exercise
            {
               
                Description = exerciseVM.Description,
                Name = exerciseVM.Name,
                ExerciseId = exerciseVM.ExerciseId,
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    exercise.Image = memoryStream.ToArray();
                }
            }

            if (ModelState.IsValid)
            {
                exerciseRepository.SaveExercise(exercise);
                TempData["Message"] = $"{exercise.Name} has been created";
                return RedirectToAction("Index", "BodyArea", bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
            }
            else
                return RedirectToAction("Index", "BodyArea", bodyAreaRepository.BodyAreas.ToList().CreateListBAreaVM(bodyPartRepository, bodyAreaRepository, dbGetter));
        }



        public ViewResult Edit(int? Id)
        {
            return View(muscleRepository.GetMusceById(Id).CreateMuscleViewModel(dbGetter));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ExerciseViewModel exerciseVM, IFormFile file)
        {
            var filePath = Path.GetTempFileName();
            Exercise exercise = new Exercise
            {
                Description = exerciseVM.Description,
                Name = exerciseVM.Name,
                ExerciseId = exerciseVM.ExerciseId,
            };
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    exercise.Image = memoryStream.ToArray();
                }
            }
            else
            {
                exercise.Image = exerciseRepository.GetExerciseById(exercise.ExerciseId).Image;
            }


            if (ModelState.IsValid)
            {
                exerciseRepository.SaveExercise(exercise);
                TempData["Message"] = $"{exercise.Name} has been saved";
                return RedirectToAction("Index", "BodyArea");
            }
            else
                return View(exerciseVM);
        }



        public ActionResult RetrieveImage(int Id)
        {

            byte[] cover = GetImageFromDataBase(Id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var photo = muscleRepository.GetMusceById(Id).Image;
            byte[] cover = photo;
            return cover;
        }
    }
}

OnTrak/Controllers/RoleAdminController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnTrak.Models.Entities.User;
using OnTrak.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnTrak.Controllers
{
    public class RoleAdminController : Controller
    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<AppUser> userManager;

        public RoleAdminController(RoleManager<IdentityRole> roleMgr, UserManager<AppUser> userMgr)
        {
            roleManager = roleMgr;
            userManager = userMgr;
        }

        public ViewResult Index() => View(roleManager.Roles);

        public IActionResult Create() => View();

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create([Required]string name) {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }

            return View("Index", roleManager.Roles);
        }

        public async Task<IActionResult> Edit(string id) {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<AppUser> members = new List<AppUser>();
            List<AppUser> nonMembers = new List<AppUser>();
            foreach (AppUser user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }return View(new RoleEditViewModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleModificationViewModel model) {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    AppUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    AppUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
            }

            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            else { return await Edit(model.RoleId); }
        }
    }
}

OnTrak/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>

    <link rel="stylesheet" asp-href-include="~/lib/bootstrap/dist/**/*.min.css" asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <meta name="viewport" content="width=device-width" />
    <link href="navbar.css" rel="stylesheet">
    <link href="carousel.css" rel="stylesheet">
    <link href="~/lib/Styles/column.css" rel="stylesheet" />
    <link href="~/lib/Styles/style.css" rel="stylesheet" />

    <title>OnTrak</title>
</head>
<body>

    @*<div class="navbar navbar-dark bg-dark" role="navigation">
            <a class="navbar-brand" href="#">On Trak</a>
        </div>
        <div>
            @RenderBody()
        </div>*@

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">On Trak</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-head" aria-controls="navbars-head" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbars-head">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("About", "Home")">About Us<span class="sr-only">(current)</span></a>
                    </li>


                    @if (User.IsInRole("Admins"))
                    {
                        <li class="nav-item">
                            <div class="dropdown">
                                <a href="#" data-toggle="dropdown" class="nav-link, navbar-dark dropdown-toggle">Admin<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a class="" href="@Url.Action("Index", "Admin")">Users</a></li>
                                    <li><a class="" href="@Url.Action("Index", "RoleAdmin")">Roles</a></li>
                                    <li><a class="" href="@Url.Action("Index", "BodyArea")">Body Areas</a></li>
                                    <li><a class="" href="@Url.Action("Index", "Exercise")">Exercise</a></li>
                                </ul>
                            </div>

                        </li>
                    }
                    @Html.Partial("_LoginPartial")
                    @*<li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown04">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>*@
                </ul>
                <form class="form-inline my-2 my-md-0">
                    <input class="form-control" type="text" placeholder="Search">
                </form>
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>

    <div class="container">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - On Trak</p>
        </footer>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/Styles/bootstrap.min.js"></script>
    <script src="~/lib/Styles/jquery.min.js"></script>
</body>
</html>

OnTrak/Views/Shared/_SmallButtonPartial.cshtml
@model OnTrak.Models.UIModel.SmallButtonModel

<a type="button" class="btn @Model.ButtonType" href="@Url.Action(Model.Action, Model.Controller)@Model.ActionParameters">
    @Model.Text
</a>

OnTrak/Views/Shared/_TableButtonsPartial.cshtml
@model OnTrak.Models.UIModel.SmallButtonModel
@using OnTrak.Models.UIModel;

<td style="width:120px;">
    <div class="btn-group" role="group">
        @Html.Partial("_SmallButtonPartial", new SmallButtonModel
        {
            Action = "Edit",
            ButtonType = "btn-primary",
            Glyph = "pencil",
            Text = "Edit",
            Id = Model.Id,
            BodyAreaId = Model.BodyAreaId,
            BodyPartId = Model.BodyPartId,

        })
        @Html.Partial("_SmallButtonPartial", new SmallButtonModel
        {
            Action = "View",
            ButtonType = "btn-primary",
            Glyph = "pencil",
            Text = "View",
            Id = Model.Id,
            BodyAreaId = Model.BodyAreaId,
            BodyPartId = Model.BodyPartId,
        })
        @Html.Partial("_SmallButtonPartial", new SmallButtonModel
        {
            Action = "Delete",
            ButtonType = "btn-danger",
            Glyph = "pencil",
            Text = "Delete",
            Id = Model.Id,
            BodyAreaId = Model.BodyAreaId,
            BodyPartId = Model.BodyPartId,
        })
    </div>
</td>